gui/yarn.lock
1. Solve archlinuxcn/repo#1950 .
=> fix: Package source of yarn install

build-in-pwsh.ps1
Add PowerShell build script to support build in Windows, Linux and macOS
=> Add PowerShell build script

.github/workflows/release.yml
Add linux/ppc64le build for release build
=> Add linux/ppc64le build

gui/src/locales/en.js
=> Try to fix EN translation

service/core/coreObj/coreObj.go, service/core/serverObj/v2ray.go
=> Allow host to be empty in httpSettings

service/conf/report/kernel.go
add report for linux kernel modules check
try to report for issue like  #349
=> feat(report): add report for linux kernel modules check

service/common/crypto.go
=> fix: resolving subscription for line-breaked base64 string

service/conf/environmentConfig.go
=> chore: add description for `--log-disable-timestamp`

Dockerfile.nightly
Update https://registry.npm.taobao.org to https://registry.npmmirror.com, Please refer to https://zhuanlan.zhihu.com/p/430580607.
=> update https://registry.npm.taobao.org to https://registry.npmmirror.com

service/go.mod, service/go.sum
More info: https://github.com/modern-go/reflect2/issues/22
=> fix: panic in go 1.18

install/universal/v2raya-lite.service
=> fix(install): v2raya-lite.service should wanted by default.target

README.md, README_zh.md
=> Update wiki links in README

install/universal/v2raya.run
=> add a runit script for v2raya.

service/core/v2ray/where/where.go
Maybe close #770. It seems that sometimes `cmd.Stdout` is written twice for two lines of output, but `onceWriter` only captures the second line of
```
V2Ray 5.1.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.19 windows/amd64)
A unified platform for anti-censorship.
```
, so the `variant` becomes `A` which is unknown.
=> fix: capture full output of v2ray

gui/src/assets/scss/reset.scss
=> Fix tip label display

gui/src/locales/pt-br.js
Added pt-br.js file for brazilian portuguese language
=> Added pt-br.js file for brazilian portuguese language

service/common/ntp/ntp.go, service/core/v2ray/v2rayTmpl.go, service/server/controller/latency.go, service/server/service/latency.go
Also check the UDP port occupation because socks5 needs it.
=> fix: port occupation when latency test

.github/workflows/release_feat_v5.yml, install/debian/conf/distributions, install/windows-inno/v2rayA-service.xml
1. add v2ray/xray packages to v2raya-apt
2. don't build mips families' pacman packages for Arch Linux MIPS port has dead for 10 years
3. update crazy-max/ghaction-github-pages to v3.2.0
4. update crazy-max/ghaction-import-gpg to v5.4.0
=> ci(release_feat_v5): some changes

gui/src/components/modalSubcription.vue, gui/src/locales/en.js, gui/src/locales/pt-br.js, gui/src/locales/zh.js, service/core/touch/touch.go, service/server/service/subscription.go
=> refactor: 允许修改订阅地址

gui/src/components/modalServer.vue, service/core/serverObj/trojan.go, service/go.sum
I don't know if Trojan works with HTTP or whatnot, but I so far got it to work with gRPC
the other stuff is not tested, and I'm not sure how the obfuscation websocket option worked (not sure if it's overlapping with this WS option I added that works the same as the gRPC)
Resolves #347
=> added Trojan GRPC capabilities and possibly more (not tested)

gui/package.json, gui/yarn.lock
=> Revert "chore(deps): bump axios from 0.21.4 to 0.28.0 in /gui"

Dockerfile.dev
This issue arises when you run a script to build a docker development environment.
`$ docker-compose -f docker-compose.dev.yml up --build`.
The following error occurs when building a docker container. 
1. `go get` to `go install`
```
=> ERROR [stage-1 3/6] RUN go get github.com/codegangsta/gin                                                                                                                                                                            0.2s
=> CACHED [v2ray 2/2] RUN ls /usr/local/share/v2ray || (mkdir -p /usr/local/share/v2ray && touch /usr/local/share/v2ray/.copykeep)                                                                                                      0.0s
------
> [stage-1 3/6] RUN go get github.com/codegangsta/gin:
#0 0.162 go: go.mod file not …
```
=> Fix: docker dev environment build

gui/src/locales/ru.js
This pull request corrects errors in the Russian translation, improving clarity and fixing grammar issues for a more consistent user experience.
=> fix: typos in russian translation

gui/package.json, gui/src/components/modalDomainsExcluded.vue, gui/src/components/modalSetting.vue, gui/src/components/modalUpdateGfwList.vue, gui/src/locales/en.js, gui/src/locales/zh.js, gui/yarn.lock, service/core/coreObj/coreObj.go, service/core/v2ray/asset/dat/gfwlist.go, service/core/v2ray/v2rayTmpl.go, service/db/configure/configure.go, service/db/configure/const.go, service/db/configure/setting.go, service/pre.go, service/server/controller/gfwlist.go, service/server/controller/inboundSniffing.go, service/server/router/index.go
new function:
1.support downloading gfwlist from custom address
2.support set domain sniffing
3.support set domain exclude
=> feat: optimize gfwlist update and support domain sniffing settings

gui/src/components/modalServer.vue, service/core/coreObj/coreObj.go, service/core/serverObj/v2ray.go
Implement support for Xray's XHTTP protocol to offer a more resilient option.
=> feat: support miminal xhttp.
