.github/workflows/dispatch_docs.yml
According to https://github.com/benc-uk/workflow-dispatch/blob/master/action.yaml#L14-L16, it is necessary to specify the branch to be triggered the workflow dispatch.
=> chore(ci): fix dispatch_docs

gui/src/node.vue
Make Operations column sortable based on servers connection status. When sorted, only connected servers on top:
desc: error > high ping > low ping > unconnected
asc: low ping > high ping > error > unconnected
=> feat: add sort function on Operations column

service/core/v2ray/process.go
fix https://github.com/v2rayA/v2rayA/issues/380
当V2ray意外退出后，iptables和dns，以及右上角的状态并不会更新，开启透明代理后可能导致系统断网
=> fix: 当V2ray意外退出后，修改系统状态

build-in-pwsh.ps1, build.sh, gui/src/locales/en.js, gui/src/locales/zh.js, gui/vue.config.js, service/go.mod, service/go.sum, service/server/router/index.go
提前将前端静态文件压缩后再embed到二进制中，可以有效减小二进制文件体积，同时减少运行时压缩开销，这在嵌入式设备上至关重要。
在我的设备上测试，二进制体积可减少25%:
唯一的问题可能是需要修改GUI的asset路径，这可能造成不兼容的改动
关于为什么brotli反而压缩率下降了：
```
Using brotli adds about 260 KB to binary size, that's why it is moved to a separate package.
```
=> optimize: 使用预压缩的前端文件以节省体积

service/conf/report/connection.go, service/core/specialMode/fakedns.go, service/core/specialMode/infra/whitelistcn.go, service/core/v2ray/asset/asset.go, service/core/v2ray/asset/dat/geoip.go, service/core/v2ray/asset/dat/geosite.go, service/core/v2ray/asset/dat/gfwlist.go, service/core/v2ray/process.go, service/core/v2ray/processManager.go, service/core/v2ray/service/service.go, service/core/v2ray/v2rayTmpl.go, service/core/v2ray/where/where.go, service/go.mod, service/go.sum, service/pre.go, service/server/controller/version.go, service/server/service/connect.go, service/server/service/setting.go
Search for (or store) v2ray assets in XDG data directories, instead of using hardcoded pathes.
Also allows different assets to be from different pathes.
pathes are searched for per asset
pathes are searched once, and the first path containing `geosite.dat` would be used
v2raya's behavior is clearly different from v2ray or xray's
it is acceptable if v2ray or xray searches a path that we do not search, with a path in precedence containing an asset of the same name, as the worst outcome would be us downloading that asset ourselves, which is the case for `/opt/share/v2ray`
however if we searches a path that v2ray or xray does not search, we may generate invalid configurations and cause confusions.
The best solution would be v2ray or xray also following XDG specification, but given the current …
=> feat: search for assets in XDG directories

gui/src/components/modalCustomPorts.vue, gui/src/locales/en.js, gui/src/locales/zh.js, service/core/v2ray/templateJson.go, service/core/v2ray/v2rayTmpl.go, service/db/configure/configure.go, service/db/configure/ports.go, service/server/service/ports.go
相关issue #88  
为了实现局域网内的全局加速，我通过路由器上的ipt2socks将需要加速的流量转发到v2raya的socks代理上，但这些流量需要在v2raya中进一步进行分流（如NetFlix等）。
目前，可以通过RoutingA规则实现，大致如下：
```
inboundTag(socks, rule) && domain(geosite:netflix) -> netflix
```
但是编写起来比较麻烦，也不太美观。
因此，参考httpWithPac，实现了socks5WithPac，用于对socks5代理流量进行分流。
=> feat: Add port for socks5 proxy with rule

service/core/serverObj/v2ray.go
修复Vmess json格式时，订阅参数中有sni无host时无法正确识别
#496
=> fix vmess sni

gui/src/components/modalServer.vue, service/core/serverObj/socks.go, service/server/service/import.go
This PR adds support for using SOCKS as a outbound server.
A new `serverObj` and corresponding GUI parts are added.
They basically mimic the existing `http` serverObj implementations with few changes, there should be no confliction to current code base.
By having SOCKS as an outbound, v2raya can chain unsupported proxy with better performance and UDP support.
Thank you! Please review.
=> Support SOCKS as outbound server.

service/core/iptables/tproxy.go
According to the [document](https://v2raya.org/docs/advanced-application/specify-container-proxy/#%E9%80%8F%E6%98%8E%E4%BB%A3%E7%90%86%E4%BD%BF%E7%94%A8-tproxy-%E6%A8%A1%E5%BC%8F), all bridged containers should access the internet directly.
However, on my Arch Linux with Docker 20.10.17 and Docker Compose 2.9.0, the default (compose) network creates a bridge interface with name like `br-xxx:`. Therefore, we should early return in the `TP_RULE` to prevent the corresponding traffic to be marked.
=> Fixed for Docker Compose (ArchLinux)

.gitignore, gui/src/components/modalServer.vue, gui/src/locales/en.js, gui/src/locales/zh.js, service/core/serverObj/shadowsocks.go
我使用的一家机场订阅遇到了和 #597 类似的情况（aes-256-gcm+simple-obfs 无法上网），但Windows 上使用最新的v2rayN 可以。我参照 v2rayN 对 obfs 的处理方式，实现了一套新的 shadowsocks plugin 处理逻辑（直接转换为相应的传输层设置）
- simple-obfs ：http 模式已通过验证
- v2ray-plugin：websocket 模式已通过验证
我已在 UI 引入了切换开关，但在处理后端切换逻辑时遇到了点问题。直接在 https://github.com/v2rayA/v2rayA/blob/288cd62a104c15d19f7e5b8f28e3cd6859da33fc/service/core/serverObj/shadowsocks.go 文件内 `import github.com/v2rayA/v2rayA/db/configure` 会导致循环导入。
@mzz2017 请教一下，有没有比较好的解决方法
=> Provide a new implement way of shadowsocks plugin.

service/db/boltdb.go, service/db/listOp.go, service/db/plainOp.go, service/db/setOp.go
Fix: #685 
As it mentioned in #685, disk writes are greatly reduced by using read-only transactions as much as possible.
=> optimize: reduce disk writes

install/aur/v2raya-bin/.SRCINFO, install/aur/v2raya-bin/PKGBUILD, install/aur/v2raya/.SRCINFO, install/aur/v2raya/PKGBUILD, install/universal/v2raya.service, service/conf/environmentConfig.go, service/conf/report/config.go
- Add a cmd `v2raya --report config` to report current config.
- generate `/etc/default/v2raya` for systemd user as `EnvironmentFile`
```bash
./v2raya --report config | sed '1,6d' | fold -s -w 78 | sed -E 's/^([^#].+)/# \1/' 
```
=> chore(config): add default env config file for systemd user

gui/src/node.vue
remove tz.guess
In case the raw time format is in `YYYY-MM-DD HH:mm:ss`
-----------
=> fix(subtime): remove timezone guess

install/universal/v2raya-lite.service, install/universal/v2raya.service
v2rayA should start after nftables, or rules made by v2rayA might be cleanup by nft.
=> v2rayA should start after nftables

.github/workflows/release_feat_v5.yml, install/universal/v2raya.default
systemd service file in package should packaged in /usr
dh_installdeb(1) automatically flags any file under the /etc directory as `conffiles`
see: https://www.debian.org/doc/manuals/maint-guide/dother.en.html#conffiles
see also #680
=> ci(debian): generate default config for systemd environment

build.sh, gui/src/components/modalServer.vue, service/core/serverObj/v2ray.go
Currently, the upstream xray project allows users to configure flow (e.g. xtls-rprx-vision) when using TLS, while v2raya lacks support for this. Please merge this PR to enhance the relevant functionality.
```json
{
"protocol": "vless",
"settings": {
"vnext": [
{
"address": "<hostname>",
"port": 443,
"users": [
{
"id": "<client id>",
"encryption": "none",
"flow": "xtls-rprx-vision"
}
]
}
]
},
"streamSettings": {
"network": "tcp",
"security": "tls"
},
"tag": "proxy"
}
```
=> Allow using flow option with TLS.

build.sh
If the value of $CurrentDir contains whitespaces, $file in `for` loop could get non-existing file paths, which in turn fails the building process.
This commit fixes that bug by discarding the entire `for` loop and running solely the `find` command with the `gzip` commanded in the `-exec` clause after file paths filtered by `-name` and `-type` predicates.
=> fix a bug in /build.sh

gui/src/node.vue
Set width for server address and server latency columns.
Colorize latency column.
the server address column max-width is set to 350 for full HD screens and larger sizes and 150px for smaller sizes.
if the server latency starts with a number it gets green and red otherwise.
=> Improve server list table columns

build-in-pwsh.ps1, build.sh, gui/package.json, gui/vue.config.js, gui/yarn.lock
* Turn on Gzip compression on the front end; 
- Use compression-webpack-plugin plugin; 
- Configure in vue.config.js 
- Enable compression only in production mode
* Remove original compression method
Compression is only enabled in the production environment, and is not enabled by default in the development environment (in fact, an error will be reported when enabled in the development environment).
The compression rules follow the previous compression rules, and the test results are the same as the previous file results.
I think this would make link testing easier for front-end and back-end development.
It can also run normally after actual packaging. It has been tested on Windows and ArchLinux (front-end running separately and overall packaging test).
_**I will help improve the …
=> Use webpack plugin to compress the files of the web panel

service/core/iptables/utils.go, service/server/service/latency.go
This issue https://github.com/v2rayA/v2rayA/issues/623 highlights an unexpected exiting problem when conducting http latency tests on IPv6-only domains. This issue persists in V2rayA 2.2.4.7 with V2Ray 5.12.1 (current latest version) on Windows 11 23H2. The log when the problem occurs is as follows:
```plaintext
2024/02/24 19:39:05.663 [I] [io.go:431]  panic: runtime error: invalid memory address or nil pointer dereference
2024/02/24 19:39:05.663 [I] [io.go:431]  [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6080d6b15f02]
2024/02/24 19:39:05.663 [I] [io.go:431]  
2024/02/24 19:39:05.663 [I] [io.go:431]  goroutine 1 [running]:
2024/02/24 19:39:05.663 [I] [io.go:431]  github.com/v2fly/v2ray-core/v5/infra/conf/synthetic/dns.getHostMapping(0x0)
2024/02/24 19:39:05.663 [I] …
```
=> Fix: Unexpected exiting when testing http latency of IPv6 only domains

gui/src/components/modalSetting.vue
The `update` button is text style. I did not recognized it is a button. I have some URL being blocked, I only can use `no split traffic` option. I asked help on Internet. I do not know why. one say the `update` is a button.
Please set it be more like a button
=> Remove "is-text" in button style

Dockerfile, Dockerfile.dev, Dockerfile.nightly
nft support was introduced with [v2.0.4](https://github.com/v2rayA/v2rayA/releases/tag/v2.0.4), this adds `nftables` package as a dependency to the docker images.
=> build the docker images with nftables

gui/src/components/modalServer.vue, service/core/coreObj/coreObj.go, service/core/serverObj/v2ray.go
Added support for the QUIC protocol in VLESS configuration
Why is the `scy` field used for the `TLS` field in the ParseVlessURL function?
I was planning to add encryption options like aes-128-gcm and chacha20-poly1305, but I noticed that the scy field is being used for TLS in the ParseVlessURL function. Could you explain the reasoning behind this usage?
---
Please review and provide feedback. Thank you!
=> Add Support for QUIC Protocol in VLESS

service/core/v2ray/processManager.go
This changes how the hook programs (mainly scripts) are called. The program used to recognize the `core-hook` and `transparent-hook` as a single executable and pass it as a whole to `os.exec`. The behavior is OK on *nix as we can use shebangs, for scripts written in Python or other interpreter-based languages, we can specify the interpreter at the very beginning of it. But it's quite a different story on Windows, only `bat` (cmd) scripts are first-class citizens, we need one of that as an intermediate to invoke what we really want to call. With this change, the `core-hook` and `transparent-hook` will be split by space and collected into an array, the final executable would be the first element in it and all other elements (if any) follow as arguments. This makes pattern like `python …
=> refactor: hook execution policy

gui/src/components/modalServer.vue, service/core/serverObj/shadowsocks.go, service/pkg/plugin/ss/ss.go
While using v2rayA with xray-core as the substitution of v2ray-core, it prompts an error says `failed to start v2ray-core: unsupported shadowsocks encryption method: 2022-blake3-aes-128-gcm` while clicking on 'start'. However, xray-core explicitly supports 2022-blake3-aes-128-gcm, 2022-blake3-aes-256-gcm and 2022-blake3-chacha20-poly1305. Therefore, there should not be this error.
I added a few modification (very few, easy to compare), and problem solved. I believe that many customers has the same problem, so hope you can check them and merge them into the main branch please. (Or if you suggest me to create a new feature branch, please let me know.)
=> Added support to protocol: 2022-blake3-aes-128-gcm and 2 more. Fixed bug while using xray-core.

gui/src/components/modalServer.vue
Every time I tried to edit my trojan node with no obfuscation, the option of obfs won't be selected for a undefined variable.
It seems that only those nodes whose type is ws/websocket will have the ability to have obfs, so just delete the map, do the judgement by if sentence.
=> fix(gui): trojan with no obfuscation won't be selected

service/core/serverObj/trojan.go
I'm not sure why the param name of Websocket Path
is serviceName now, but the v2rayN export format is like: trojan://passwd@host:port?security=tls&type=ws&host=foo.bar.com&path=%2Fpath#remarks.
=> change trojan ws path url param name from "serviceName" to "path" to fit v2rayN's export format.

.github/workflows/release_main.yml, install/docker/docker_helper.sh
Add riscv64 to docker build.
Tested build with the following command successfully:
```bash
$ export version=2.2.6.2
$ sed -i "s|Realv2rayAVersion|$version|g" install/docker/docker_helper.sh
$ docker build -t ngc7331/v2raya:latest --platform linux/riscv64 -f install/docker/Dockerfile.Action --push .
```
Image: https://hub.docker.com/repository/docker/ngc7331/v2raya/tags
Tested on a Milk-V Mars board and everything works fine:
```bash
$ neofetch
_,met$$$$$gg.          user@MarsCM 
,g$$$$$$$$$$$$$$$P.       ------------ 
,g$$P"     """Y$$.".        OS: Debian GNU/Linux trixie/sid riscv64 
,$$P'              `$$$.     Host: Milk-V Mars CM eMMC 
',$$P       ,ggs.     `$$b:   Kernel: 5.15.0-xu.2 
`d$$'     ,$P"'   .    $$$    Uptime: 10 mins 
$$P      d$'     ,    $$P    Packages: 1251 (dpkg) …
```
=> chore(docker,ci): add riscv64 to docker build

service/core/v2ray/process.go
- On older devices, 15 seconds is not enough time to start xray, which will result in webui showing startup failure before xray is successfully started, at which point the already started xray process will not be destroyed by v2raya, which will result in memory exhaustion by xray if webui is clicked to start multiple times.
=> fix: core startup timeout on old devices

service/core/iptables/systemProxy_windows.go
// Deprecated: Use [SyscallN] instead.
func Syscall(trap, nargs, a1, a2, a3 uintptr) (r1, r2 uintptr, err Errno)
// Deprecated: Use [SyscallN] instead.
func Syscall6(trap, nargs, a1, a2, a3, a4, a5, a6 uintptr) (r1, r2 uintptr, err Errno)
windows Syscall is deprecated, use SyscallN
=> fix windows Syscall Deprecated
